groups:
- name: IVE
  youtube_channel_ids:
  - UC-Fnix71vRP64WXeo0ikd0Q
  itunes_artist_ids:
  - '1594159996'
  google_news_query: IVE kpop
- name: Red Velvet
  youtube_channel_ids:
  - UCk9GmdlDTBfgGRb7vXeRMoQ
  itunes_artist_ids:
  - '906961899'
  google_news_query: Red Velvet kpop
- name: aespa
  youtube_channel_ids:
  - UC9GtSLeksfK4yuJ_g1lgQbg
  itunes_artist_ids:
  - '1540251304'
  google_news_query: aespa kpop
- name: TWICE
  youtube_channel_ids:
  - UCzgxx_DM2Dcb9Y1spb9mUJA
  itunes_artist_ids:
  - '1203816887'
  google_news_query: TWICE kpop
- name: le sserafim
  youtube_channel_ids:
  - UCs-QBT4qkj_YiQw1ZntDO3g
  itunes_artist_ids:
  - '1616740364'
  google_news_query: le sserafim kpop
- name: Gfriend
  youtube_channel_ids:
  - UCRDd3x33kfF0IW6g2MRUkRw
  itunes_artist_ids:
  - '958416186'
  google_news_query: Gfriend kpop
- name: New Jeans
  youtube_channel_ids:
  - UCMki_UkHb4qSc0qyEcOHHJw
  itunes_artist_ids:
  - '1635469693'
  google_news_query: New Jeans kpop
